### ISSUE TITLE
question about "Compute function: Partition => Iterator[T]"

### ISSUE THREAD

**Issue by xianzheTM** [databricks/LearningSparkV2#72]
In the subsection "spark: what's next an rdd?", the author says "Spark has no knowledge of the specific data type in T".
But I found that lambda in rdd contains type information. So what does this sentence mean?
![image](https://user-images.githubusercontent.com/25103583/157393794-29ffe319-40a1-4ded-b25a-40f63c9e2cfa.png)

**Comment by dmatrix** [comment]
@xianzheTM 

> "Spark has no knowledge of the specific data type in T"
I think it would be fitting to listen to [Michael Armbrust's description](https://youtu.be/1a4pgYzeFwE?t=50) of what he meant by structure in Spark, in particular to this reference to the Iterator T.

The Iterator is really the data that's going to be stored inside the RDD. There are two properties of this iterator:
 * the computation is opaque
 * the data it holds is opaque, that is an opaque java, scala, or python object. 

Because of its opacity, Spark cannot peak into it to look at a specific column to ascertain what can I do to optimize. The best it can do since it's a generic JVM object is to serialize.

The term "type" is broadly used here, and not to be misconstrued with the exact content type RDD field types.

**Comment by xianzheTM** [comment]
@dmatrix
My understanding is that although there is exact type information in RDD, Spark has not optimized according to this type (after all, it is not practical to rely on this to optimize), so the types in RDD are still opaque to Spark.

**Comment by dmatrix** [comment]
Yes, the RDD has the exact scalar types (int, double, string), whereas the DataFrames have supported Structured Spark types (BinaryType, DateType, ArrayType, MapType, StructType, StructField); with these structured types in a DataFrame, Spark can use its efficient SerDe for passing data between functions or across clusters and optimize or re-arrange how operations are rearranged when constructing a DAG.

I hope that clears it.

**Comment by xianzheTM** [comment]
@dmatrix 
I see. Thank you for your answer.
